#!/usr/bin/env bash
# configure web-02 to be identical to web-01.

sudo apt update -y

sudo apt-get install -y nginx

sudo ufw allow 'NGINX HTTP'

sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www

# Create index and 404 pages
echo 'Hello World!' | sudo tee /var/www/html/index.html >/dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html >/dev/null

server_config=$(
    cat <<EOF
server{
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me) {
        rewrite ^ https://youtube.com permanent;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF
)

echo "$server_config" | sudo tee /etc/nginx/sites-available/default >/dev/null 2>&1

sudo service nginx restart
