#!/usr/bin/env bash

# Install and configure HAproxy on your lb-01 server.

printf %s "
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 465161-web-01 54.167.86.214:80 check
    server 465161-web-02 100.25.38.121:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null 2>&1

sudo service haproxy restart
