#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

backend="\
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 465161-web-01 54.167.86.214:80 check
    server 465161-web-02 100.25.38.121:80 check
"
# Update and upgrade the system
sudo apt-get -y update
sudo apt-get -y upgrade

# # Enable a `dedicated PPA` with the following command:
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8

# # Installing haproxy
sudo apt-get install haproxy

echo "$backend" >>/etc/haproxy/haproxy.cfg >/dev/null 2>&1

sudo service haproxy restart
