#!/usr/bin/env bash
# Delete `myscript.pid` when encounter SIGQUIT signal
while true
do
    echo "To infinity and beyond"
    trap 'echo "I hate the kill command"' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/myscript.pid' SIGQUIT
done