#!/usr/bin/env bash
# displays Best School 10 times, 
# but for the 9th iteration, displays Best School and then Hi on a new line.
a=0;

while [ "$a" -lt 10 ]
do
    if [ "$a" -eq 3 ]
    then
        echo "bad luck"
    elif [ "$a" -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((a++))
done
