#!/usr/bin/env bash
# displays numbers from 1 to 20
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

a=1;

while [ "$a" -lt 21 ]
do
    case $a in 5)
    echo "bad luck from China"
    ;;
    10)
    echo "bad luck from Japan"
    ;;
    18)
    echo "bad luck from Italy"
    ;;
    esac
    echo "$a"
    ((a++))
done
